title: FluentDefaults Documentation
description: Documentation for the FluentDefaults library
theme: jekyll-theme-cayman
markdown: kramdown

# Site navigation
nav:
  - title: "Home"
    url: "/"
  - title: "Dependency Injection"
    url: "/di"

# Use the same navigation for the sidebar
sidebar: *nav

# Breadcrumb
breadcrumb_home_label : "Home"
breadcrumb_separator  : ">"