title: Fluent defaults
description: Documentation for the FluentDefaults library
markdown: kramdown

# Sidebar configuration
sidebar:
  nav:
    - title: "Home"
      url: "/"
    - title: "Dependency Injection"
      url: "/di.html" 

# Breadcrumb
breadcrumb_home_label : "Home"
breadcrumb_separator  : ">"