title: Fluent defaults
description: Documentation for the FluentDefaults library
theme: jekyll-theme-cayman
markdown: kramdown

# Sidebar configuration
sidebar:
  nav:
    - title: "Home"
      url: "/fluent-defaults"
    - title: "Dependency Injection"
      url: "di" 

# Breadcrumb
breadcrumb_home_label : "Home"
breadcrumb_separator  : ">"