title: Fluent defaults
description: Documentation for the FluentDefaults library
markdown: kramdown

# Sidebar configuration
sidebar:
  nav:
    - title: "Home"
      url: "/fluent-defaults"
    - title: "Dependency Injection"
      url: "di"
    - title: "Complex properties"
      url: "complex"
    - title: "Collections"
      url: "collection"
    - title: "Async"
      url: "async"

# Breadcrumb
breadcrumb_home_label : "Home"
breadcrumb_separator  : ">"